### ISSUE TITLE
评论

### ISSUE THREAD

**Issue by U1611** [OuyangWenyu/hydro-model-xaj#15]
水平有限，还没跑起来。wiki里面对模型原理的讲解非常详细，有很多探究和思考。比较惊叹贡献者的知识体系和数学功底。

**Comment by OuyangWenyu** [comment]
谬赞了，可能写的有问题，欢迎指正

**Comment by U1611** [comment]
请教一下，KI、KG、CI、CG这四个参数在日模型和次洪模型之间是如何转化的。另外，为什么使用SCE-UA算法率定出来的参数均介于0~1，是依据取值范围进行了归一化处理吗？

**Comment by U1611** [comment]
![包气带蓄水容量曲线](https://user-images.githubusercontent.com/105044033/168858772-79d125aa-ccc4-430c-b7c8-c893d7ddbff5.png)

**Comment by U1611** [comment]
感谢作者的用心。

**Comment by OuyangWenyu** [comment]
次洪那块涉及场次划分啥的  开始写这个代码的时候手头没有现成代码 所以没包含进来 ；模型参数率定的时候都做了归一化处理，方便代码统一，进入模型之后会根据设置的范围反归一化回去

**Comment by OuyangWenyu** [comment]
mizuRoute那块是因为写了和这个论文类似的代码：https://doi.org/10.1038/s41467-021-26107-z   所以借鉴的这个论文里面的做法

**Comment by OuyangWenyu** [comment]
5mm那块是参考的书上那么写的。分水源那块应该是一个长方体水箱一直在随着产流的大小弹性缩放，即假定了一个总容量恒定的长方体水箱做自由水蓄水水库，底面是FR，高度是S，所以有FR0*S0 = FR * S，因为FR在随着R变，所以S也得变。这个时候计算上默认R是时段初进入的了，因为如果按时段平均的话，也就是FR和S都是时段均值的话，就意味着时段内S不变了，可是时段内计算的时候又需要S变，才能来分水源，所以只能按时段初来。所以可以想象到有一个时段R小，下一个R特别大，这个时候长方体就有点突变的意思，这时候划分到5mm，这个突变就相对平滑一些，书上说的不划分5mm差分误差大可能是这个意思。不过书上没给出一些实际例子做对比论证，感觉不是非常令人信服。因为我自己是在日尺度上做了一些简单数值实验，感觉概念性水文模型的能力有限，影响的预测精度的因素也比较多，所以不是太想搞这么复杂，场次的话可能这个影响会更大一些。

**Comment by U1611** [comment]
> mizuRoute那块是因为写了和这个论文类似的代码：https://doi.org/10.1038/s41467-021-26107-z 所以借鉴的这个论文里面的做法

看不懂。不过这篇文章里面用到了SCE-UA算法，你好像也有研究这个算法。实现过这个算法，但在实际应用中不是特别理想，不知道什么原因。

**Comment by U1611** [comment]
只做过概念性水文模型，现在有其他预报精度更高的模型吗？

**Comment by U1611** [comment]
好像也有很多数据驱动模型，用来做预报。

**Comment by U1611** [comment]
> mizuRoute那块是因为写了和这个论文类似的代码：https://doi.org/10.1038/s41467-021-26107-z 所以借鉴的这个论文里面的做法

作者好像也有参与这个

**Comment by U1611** [comment]
> 

这么分析很有道理，5mm划分水源应该也是必要的。python上好像有好多别人写好的现成的函数，看你卷积和伽马函数都是直接调用的。

**Comment by OuyangWenyu** [comment]
> 好像也有很多数据驱动模型，用来做预报。

https://github.com/mhpi/hydroDL  
https://github.com/neuralhydrology/neuralhydrology

**Comment by OuyangWenyu** [comment]
> 只做过概念性水文模型，现在有其他预报精度更高的模型吗？

https://github.com/UW-Hydro/VIC
https://github.com/WatershedModels/SWAT
不一定精度更高 但是模型挺多的 可以自己搜搜

**Comment by OuyangWenyu** [comment]
> > mizuRoute那块是因为写了和这个论文类似的代码：https://doi.org/10.1038/s41467-021-26107-z 所以借鉴的这个论文里面的做法
> 
> 作者好像也有参与这个

没有

**Comment by U1611** [comment]
> > 好像也有很多数据驱动模型，用来做预报。
> 
> https://github.com/mhpi/hydroDL https://github.com/neuralhydrology/neuralhydrology

这两个好像很厉害哦

**Comment by U1611** [comment]
> > 只做过概念性水文模型，现在有其他预报精度更高的模型吗？
> 
> https://github.com/UW-Hydro/VIC https://github.com/WatershedModels/SWAT 不一定精度更高 但是模型挺多的 可以自己搜搜

哦，这两个模型很有名，但没用过。我了解一下。

**Comment by U1611** [comment]
深度学习和神经网络这两个模型是什么关系呢，你推荐的文章里面好像即有深度学习，又有神经网络

**Comment by U1611** [comment]
我看论文有点慢

**Comment by U1611** [comment]
毕业了以后很少看这些。

**Comment by U1611** [comment]
看你的文章，好像是在大尺度范围内做预报，确定性系数能达到0.7几，有的能达到0.8几，现在深度学习、智能算法之类的能达到这种程度，也是很不错的哦

**Comment by U1611** [comment]
单个流域人工调参，达到0.75、0.8以上都不容易

**Comment by U1611** [comment]
而且好像还是超长时间序列，只用了几个小时就算完了，你们那个计算机也好厉害啊

**Comment by U1611** [comment]
是日模吗？一天一个数据的那种

**Comment by U1611** [comment]
而且无资料的地区也能做预报

**Comment by U1611** [comment]
> > 只做过概念性水文模型，现在有其他预报精度更高的模型吗？
> 
> https://github.com/UW-Hydro/VIC https://github.com/WatershedModels/SWAT 不一定精度更高 但是模型挺多的 可以自己搜搜

这些模型好像更复杂，考虑的对水循环影响的因素更多，适用范围、情况更广。
东西有点多，可能要花一段时间才能有所了解吧。

**Comment by U1611** [comment]
> > 好像也有很多数据驱动模型，用来做预报。
> 
> https://github.com/mhpi/hydroDL https://github.com/neuralhydrology/neuralhydrology
这些好像都挺难的，似乎大数据挖掘、深度学习之类的在各领域的应用需要很多人去研究，国家是不是也在往这方面引导，投入了很多。好像这两年有些高校开设了人工智能研究院。

**Comment by U1611** [comment]
可能水文上有些难以解决的问题，以后通过这些途径可以解决。

**Comment by U1611** [comment]
> > 只做过概念性水文模型，现在有其他预报精度更高的模型吗？
> 
> https://github.com/UW-Hydro/VIC https://github.com/WatershedModels/SWAT 不一定精度更高 但是模型挺多的 可以自己搜搜

你用过吗，这两个学起来好像都挺难的。

**Comment by U1611** [comment]
> > 好像也有很多数据驱动模型，用来做预报。
> 
> https://github.com/mhpi/hydroDL https://github.com/neuralhydrology/neuralhydrology

没怎么接触过数据驱动模型，贡献者是专门研究这个的吗

**Comment by U1611** [comment]
> > > mizuRoute那块是因为写了和这个论文类似的代码：https://doi.org/10.1038/s41467-021-26107-z 所以借鉴的这个论文里面的做法
> > 
> > 
> > 作者好像也有参与这个
> 
> 没有

这是作者所在的课题组的成果吗

**Comment by U1611** [comment]
你好像还另外写了一个gr4j模型，有做过试验吗，模拟效果怎么样？和新安江模型比，哪个效果更好一点？

**Comment by U1611** [comment]
这个GR4J模型也是概念性水文模型诶。难怪作者会感觉概念性模型能力有限，原来是做了充分的论证的

**Comment by U1611** [comment]
阅读作者的源码，感觉代码写得很有章法，注释完整，可读性强。对比一下我的模型就写得不那么漂亮了。多读一下作者的，有助于提高我的代码水平。

**Comment by U1611** [comment]
> > 好像也有很多数据驱动模型，用来做预报。
> 
> https://github.com/mhpi/hydroDL https://github.com/neuralhydrology/neuralhydrology

之前用一种神经网络模型做过一个预报，这个模型对实测流量过程的模拟、预报都挺不错的。不过我们做的规模比较小，比较简单。

**Comment by U1611** [comment]
> > > mizuRoute那块是因为写了和这个论文类似的代码：https://doi.org/10.1038/s41467-021-26107-z 所以借鉴的这个论文里面的做法
> > 
> > 
> > 作者好像也有参与这个
> 
> 没有

看你们好像是用的是相同的实验数据，也写了和论文里面类似的代码，所以以为你也有参与。

**Comment by U1611** [comment]
> > > 只做过概念性水文模型，现在有其他预报精度更高的模型吗？
> > 
> > 
> > https://github.com/UW-Hydro/VIC https://github.com/WatershedModels/SWAT 不一定精度更高 但是模型挺多的 可以自己搜搜
> 
> 你用过吗，这两个学起来好像都挺难的。

如果你会用，有机会的话向你请教一下，想学着用用。

**Comment by U1611** [comment]
> > > 只做过概念性水文模型，现在有其他预报精度更高的模型吗？
> > 
> > 
> > https://github.com/UW-Hydro/VIC https://github.com/WatershedModels/SWAT 不一定精度更高 但是模型挺多的 可以自己搜搜
> 
> 你用过吗，这两个学起来好像都挺难的。

如果你会用，有机会的话向你请教一下，想学着用用。

**Comment by U1611** [comment]
文献阅读能力欠缺，看得比较慢。看你推荐的论文，收获颇丰。还有没有其它好文章？

**Comment by U1611** [comment]
> mizuRoute那块是因为写了和这个论文类似的代码：https://doi.org/10.1038/s41467-021-26107-z 所以借鉴的这个论文里面的做法

以前在学校，老师说课本上的很多方法都很老了，过时了。当时没概念，现在看看确实有好多先进的方法，课本更新没跟上。

**Comment by U1611** [comment]
> > mizuRoute那块是因为写了和这个论文类似的代码：https://doi.org/10.1038/s41467-021-26107-z 所以借鉴的这个论文里面的做法
> 
> 看不懂。不过这篇文章里面用到了SCE-UA算法，你好像也有研究这个算法。实现过这个算法，但在实际应用中不是特别理想，不知道什么原因。

这篇文章说模型参数优选的问题可以从率定发展到参数学习，效果优于现存的率定方法。以前老师谈到这个问题时，说得找到一个类似于从太空俯瞰地球，一下子就看出珠穆朗玛峰是地球最高峰的方法才行。现在又有新方法代替老方法了哦。

**Comment by U1611** [comment]
> mizuRoute那块是因为写了和这个论文类似的代码：https://doi.org/10.1038/s41467-021-26107-z 所以借鉴的这个论文里面的做法

这篇文章，发表在这种杂志上，应该是很有分量的吧，是不是

**Comment by U1611** [comment]
贡献者是那里人？

**Comment by U1611** [comment]
> > > > mizuRoute那块是因为写了和这个论文类似的代码：https://doi.org/10.1038/s41467-021-26107-z 所以借鉴的这个论文里面的做法
> > > 
> > > 
> > > 作者好像也有参与这个
> > 
> > 
> > 没有
> 
> 看你们好像是用的是相同的实验数据，也写了和论文里面类似的代码，所以以为你也有参与。

因为看你的论文和这篇文章的通讯作者是同一个人，而且其他作者也有相同的人，推断你们是同一个导师下面的，同一个实验室同一个课题组研究的东西一般都会有一些交叉重叠，大方向一致，同门之间会互相协作，再加上使用相同的实验数据，实现过相似的功能，觉得你也有可能参与过，觉得真棒

**Comment by U1611** [comment]
说看论文慢，毕业后很少看，那现在就看得更慢了。希望你不要觉得我太慢了。

**Comment by OuyangWenyu** [comment]
> 基本等于没用过

**Comment by OuyangWenyu** [comment]
如果你有跟这个代码无关的问题 可以邮件联系我  这里我直接关闭这个问题啦 谢谢讨论
