### ISSUE TITLE
请教一个问题

### ISSUE THREAD

**Issue by WZLlin** [OuyangWenyu/hydro-model-xaj#2]
在运行test.py 的时候程序报错：没有hydroeval 和 platypus 模块  。 请问这两个是什么库？
在终端中pip install 对应的库过后，任然找不到对应的子模块

**Comment by YasinLiu** [comment]
@WZLlin HydroEval: https://pypi.org/project/hydroeval/ ;Platypus: https://platypus.readthedocs.io/en/latest/getting-started.html#installing-platypus

**Comment by OuyangWenyu** [comment]
暂时不太规范，后面我会把requirement.txt加上

**Comment by WZLlin** [comment]
你好，按照《水文预报》包为民，这本书上的计算时段末的自由水蓄量的公式： S1 = S(1-KI-KG)  ，而您在代码中写道的公式： s = s - (kss_period + kg_period) / fr   ，暂时有点不明白。
<img width="629" alt="捕获" src="https://user-images.githubusercontent.com/54438131/83765951-5fccd080-a6ae-11ea-9aa1-bba70f17b4a8.PNG">

**Comment by WZLlin** [comment]
<img width="629" alt="捕获" src="https://user-images.githubusercontent.com/54438131/83766021-72470a00-a6ae-11ea-8f2f-424eef199949.PNG">

**Comment by OuyangWenyu** [comment]
时间太久了，我有点忘了，不过细节可以参考 https://github.com/OuyangWenyu/hydro-model-xaj/wiki 里面写的文字，还有我新上传的一个写这个代码之前的一个手写的略潦草的简单推导笔记。

**Comment by zibuyu-lb** [comment]
> 在运行test.py 的时候程序报错：没有hydroeval 和 platypus 模块 。 请问这两个是什么库？
> 在终端中pip install 对应的库过后，任然找不到对应的子模块

您好，请问你后续解决了吗？我也是在pip安装后还是找不到这个模块？

**Comment by WZLlin** [comment]
已解决，------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;zibuyu-lb&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年11月23日(星期一) 晚上7:43
收件人:&nbsp;&quot;OuyangWenyu/hydro-model-xaj&quot;<hydro-model-xaj@noreply.github.com&gt;;
抄送:&nbsp;&quot;治林&quot;<897048956@qq.com&gt;;&quot;Mention&quot;<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [OuyangWenyu/hydro-model-xaj] 请教一个问题 (#2)

**Comment by YasinLiu** [comment]
> > 在运行test.py 的时候程序报错：没有hydroeval 和 platypus 模块 。 请问这两个是什么库？
> > 在终端中pip install 对应的库过后，任然找不到对应的子模块
> 
> 您好，请问你后续解决了吗？我也是在pip安装后还是找不到这个模块？

Python 3.7.0
pip 20.2.4 
![image](https://user-images.githubusercontent.com/34810777/99960922-63185d80-2daf-11eb-97a8-0cad517ebda4.png)

**Comment by WZLlin** [comment]
> > 在运行test.py 的时候程序报错：没有hydroeval 和 platypus 模块 。 请问这两个是什么库？
> > 在终端中pip install 对应的库过后，任然找不到对应的子模块
> 
> 您好，请问你后续解决了吗？我也是在pip安装后还是找不到这个模块？

HydroEval: https://pypi.org/project/hydroeval/ ;Platypus: https://platypus.readthedocs.io/en/latest/getting-started.html#installing-platypus

**Comment by WZLlin** [comment]
> > > 在运行test.py 的时候程序报错：没有hydroeval 和 platypus 模块 。 请问这两个是什么库？
> > > 在终端中pip install 对应的库过后，任然找不到对应的子模块
> > 
> > 
> > 您好，请问你后续解决了吗？我也是在pip安装后还是找不到这个模块？
> 
> Python 3.7.0
> pip 20.2.4
> ![image](https://user-images.githubusercontent.com/34810777/99960922-63185d80-2daf-11eb-97a8-0cad517ebda4.png)

HydroEval: https://pypi.org/project/hydroeval/ ;Platypus: https://platypus.readthedocs.io/en/latest/getting-started.html#installing-platypus

**Comment by OuyangWenyu** [comment]
不好意思！暂时还没有维护这个repo的安排，如果需要python环境安装的教程，可以参考这里：
https://github.com/OuyangWenyu/hydrus/blob/master/1-basic-envir/2-python-envir.md

治林 <notifications@github.com> 于2020年11月24日周二 下午4:58写道：

**Comment by OuyangWenyu** [comment]
已经加了environment.yml文件，可以使用conda直接创建环境
