### ISSUE TITLE
运行错误

### ISSUE THREAD

**Issue by Chu-Orion** [OuyangWenyu/hydro-model-xaj#27]
你好，在按照.md文件运行时出现了如下的错误：
![image](https://github.com/OuyangWenyu/hydro-model-xaj/assets/126547011/667954fe-b95b-4035-99f6-de3b0bd32e1a)
请问这个应该怎么解决？（来自python小白的真诚发问）

**Comment by OuyangWenyu** [comment]
terminal打开之后，先输入cmd.exe，再输入conda activate xaj （如果没安装环境，看下README.md，先把环境装好），然后再运行。

**Comment by Chu-Orion** [comment]
OK，谢谢

**Comment by Chu-Orion** [comment]
已成功运行，感谢！！！
