### ISSUE TITLE
关于divide_source和split_flow这两部分的完善计划询问

### ISSUE THREAD

**Issue by leehombin** [OuyangWenyu/hydro-model-xaj#5]
Ouyang你好，我目前也从事新安江水文模型的相关研究，有幸学习到您的代码。在研读wiki中实测径流分析模块时，发现缺少退水曲线和洪水分割这两部分的代码。而我自身编程水平有限，还在学习作者的思路中，因此想请问作者什么时候更新这部分的code，或者我们可以交流探讨一下。

**Comment by OuyangWenyu** [comment]
新版本更新了，这回是相对来说能运行的了，代码也增加了注释，应该更容易明白一些

**Comment by OuyangWenyu** [comment]
> Ouyang你好，我目前也从事新安江水文模型的相关研究，有幸学习到您的代码。在研读wiki中实测径流分析模块时，发现缺少退水曲线和洪水分割这两部分的代码。而我自身编程水平有限，还在学习作者的思路中，因此想请问作者什么时候更新这部分的code，或者我们可以交流探讨一下。

新版本更新了，这回是相对来说能运行的了，代码也增加了注释，应该更容易明白一些
